[package]
name = "ratrace"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
rusqlite = "0.31.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.24.0"
lazy_static = "1.5.0"
directories = "5.0.1"

